### ISSUE TITLE
新bug，请问如何解决...

### ISSUE THREAD

**Issue by Liu-zhi-chao** [liyown/get_bibtex#2]
from apiModels.get_bibtex_from_google_scholar import GetBibTexFromGoogleScholar
  File "D:\anaconda\Lib\site-packages\apiModels\get_bibtex_from_google_scholar.py", line 4, in <module>
    from serpapi import GoogleSearch
ImportError: cannot import name 'GoogleSearch' from 'serpapi' (D:\anaconda\Lib\site-packages\serpapi\__init__.py)

我在您的知乎文章评论区也看到了同样的问题，serpapi 已经安装了。

**Comment by liyown** [comment]
我看看哈

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月20日 17:24 |
| 收件人 | liyown/get_bibtex ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [liyown/get_bibtex] 新bug，请问如何解决... (Issue #2) |

from apiModels.get_bibtex_from_google_scholar import GetBibTexFromGoogleScholar


File "D:\anaconda\Lib\site-packages\apiModels\get_bibtex_from_google_scholar.py", line 4, in
from serpapi import GoogleSearch
ImportError: cannot import name 'GoogleSearch' from 'serpapi' (D:\anaconda\Lib\site-packages\serpapi_init_.py)

我在您的知乎文章评论区也看到了同样的问题，serpapi 已经安装了。

**Comment by Liu-zhi-chao** [comment]
已解决，代码已经跑通。使用pip install google-search-results安装这个包，而不是 pip install serpapi
感谢您的回复以及优秀的工作！

**Comment by liyown** [comment]
👍

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月20日 17:27 |
| 收件人 | liyown/get_bibtex ***@***.***> |
| 抄送人 | liuyaowen ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [liyown/get_bibtex] 新bug，请问如何解决... (Issue #2) |

已解决，代码已经跑通。使用pip install google-search-results安装这个包，而不是 pip install serpapi
感谢您的回复以及优秀的工作！

**Comment by liyown** [comment]
我在知乎回复一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月20日 17:27 |
| 收件人 | liyown/get_bibtex ***@***.***> |
| 抄送人 | liuyaowen ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [liyown/get_bibtex] 新bug，请问如何解决... (Issue #2) |

已解决，代码已经跑通。使用pip install google-search-results安装这个包，而不是 pip install serpapi
感谢您的回复以及优秀的工作！
