### ISSUE TITLE
你好，关于返回bibtex格式的文献问题。

### ISSUE THREAD

**Issue by Liu-zhi-chao** [liyown/get_bibtex#3]
您在readme中提到若需要返回bibtex格式的文献，则需要需要设置代理服务器。请问这步的具体步骤应该怎么弄？因为本人没有接触过服务器相关知识，期待您的回复，十分感谢！

**Comment by liyown** [comment]
你使用我后面2024.4.16更新的使用方法，里面加了DBLP接口，很少有文献找不到了，就算找不到（如果同时使用crossref和dblp，很少很少的），建议去google schalar再手动查一下，代理服务器需要你购买了，还要会搭梯子，有点复杂。
